---
title: "practice-thurs"
author: "Tasha Quintana"
date: "2023-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read libraries

```{r, warning=FALSE, message=FALSE}
library(readr)
library(dplyr)
library(sf)
library(ggplot2)
library(scales)
library(leaflet)
library(ggmap)
```

## Download data

```{r download data}

pika <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-nwt.268.1&entityid=43270add3532c7f3716404576cfb3f2c")
elevation <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-nwt.268.1&entityid=6a10b35988119d0462837f9bfa31dd2f")

# glimpse(pika)
# glimpse(elevation)

```

## Explore data

```{r explore data}

colnames(pika)
colnames(elevation)

class(pika)
class(elevation)

```

## Clean data

```{r clean data}

## clean pika

pika_clean <- pika %>% 
  select(-Notes,
         -Vial,
         -Plate,
         -Biweek)

pika_clean <- pika_clean %>% 
  mutate(
    Station = as.factor(Station),
    Site = as.factor(Site),
    Sex = as.factor(Sex)
  )

unique(pika_clean$Site)

pika_clean <- pika_clean %>% 
  mutate(
    Site = recode(Site,
                  CG = "Cable Gate", 
                  WK = "West Knoll", 
                  LL = "Long Lake")
  )

pika_clean <- pika_clean %>% 
  relocate(Site, .before = Station) %>% 
  relocate(Sex, .after = UTM_Northing)

## clean elevation

elevation_clean <- elevation %>% 
  select(Station, 
         Elev_M) %>% 
  mutate(
    Station = as.factor (Station)
  )
  

```

## Join tables

```{r}

pikas <- pika_clean %>% 
  full_join(y = elevation_clean,
            by = "Station")

glimpse(pikas)
```

## Changing data table pikas to sf

```{r}

pikas_sf <- st_as_sf(x = pikas,
                     coords = c("UTM_Easting", "UTM_Northing"))

class(pikas_sf)
st_crs(pikas_sf)

pikas_sf <- st_set_crs(pikas_sf, 26913)

```

## Basic mapping

```{r basic mapping }

ggplot(data = pikas_sf)+
  geom_sf(aes(color = Site, shape = Site), alpha = 0.6)+
  theme_bw()+
  labs(
    title = "Location of Pika Sampling Stations",
    subtitle = "Niwot Ridge LTER",
    x = "Latitute (Degrees)",
    y = "Longitude (Degrees)"
  ) +
  theme(axis.text.x = element_text(angle = 30))

```

## Reproject 

```{r}

pikas_sf_4326 <- st_transform(pikas_sf, 4326)

```

## Bounding box

```{r}

nwt_bbox <- c(left = -105.65, bottom = 40.04, right = -105.55, top = 40.1)

```

## Creating basemap

```{r creating basemap}

nwt_basemap <- get_stamenmap(bbox = nwt_bbox, zoom = 13, maptype = "terrain")

ggmap(nwt_basemap)

```

## Adding basemap to map

```{r adding basemap}

ggmap(nwt_basemap) +
  geom_sf(pikas_sf_4326,
          mapping = aes(color = Site, shape = Site),
          inherit.aes = FALSE) +
  theme_light() +
  labs(
    title = "Pikas!! They're everywhere!",
    subtitle = "Seriously, folks.",
    x = "Longitude (Degrees)",
    y = "Latitude (Degrees)"
  ) +
  scale_color_manual(values = c("khaki", "firebrick", "aquamarine"))

```

