---
title: "Cleaning and Wrangling Data"
author: "Tasha Quintana"
date: "2023-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages

```{r load packages, warnings = FALSE, message = FALSE}
library(dplyr)
library(tidyr)
library(readr)
```


# Introduciton

About the data: This data was downloaded from [here](https://knb.ecoinformatics.org/view/df35b.304.2).

## Read data

```{r read data, warnings = FALSE, message = FALSE}

catch_original <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")

```

## Explore data

```{r explore, eval=FALSE, echo=FALSE}

colnames(catch_original)

head(catch_original)

summary(catch_original)

unique(catch_original$Year)

sort(unique(catch_original$Year))

sort(unique(catch_original$Region))

```

# Clean and reshape data

## Selecting and removing columns with `select()`

```{r select}

catch_data <- catch_original %>% 
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)

head(catch_data)

```

## Check column types

```{r checking}

glimpse(catch_data)

```

## Changing column types using mutate

```{r changing column types}

catch_clean <- catch_data %>%
  mutate(Chinook = as.numeric(Chinook))

head(catch_clean)

```

## Checking NA

```{r}

i <- which(is.na(catch_clean$Chinook))

catch_data[i,]

```

## Fixing Chinook column

```{r}
catch_clean <- catch_data %>% 
  mutate(Chinook = if_else(Chinook == "I", 
                           "1",
                           Chinook),
         Chinook = as.numeric(Chinook))

## Check
catch_clean[i,]

head(catch_clean)

```


## Reshape data

```{r}




```

