---
title: "Intro to Data Visualization"
author: "Tasha Quintana"
date: "2023-04-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages

```{r load packages, warning=FALSE, message=FALSE}

library(dplyr)
library(readr)
library(tidyr)
library(forcats)
library(ggplot2)
library(leaflet)
library(DT)
library(scales)

```

## Read data

Downloaded from https://knb.ecoinformatics.org/view/doi%3A10.5063%2FP26WJJ on 4/5/23.

```{r read data}

## from https://knb.ecoinformatics.org/view/doi%3A10.5063%2FP26WJJ and accessed on 4/5/23

escapement <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e")

```

## Explore data

```{r explore data}

colnames(escapement)

glimpse(escapement)

range(escapement$sampleDate)

unique(escapement$Species)

```

## Getting data ready to plot

```{r data for plotting}

annual_esc <- escapement %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarize(escape = sum(DailyCount)) %>% 
  filter(Species %in% c("Chinook", "Sockeye", "Pink", "Coho", "Chum"))

unique(annual_esc$Species)
head(annual_esc)
  
```

## Plotting with `ggplot`

### Essential components

```{r essentials}

## Option 1
ggplot(data = annual_esc,
       aes(x = Species,
           y = escape))+
  geom_col()

## Option 2
ggplot(data = annual_esc)+
  geom_col(aes(x = Species,
               y = escape))

## Option 3
ggplot()+
  geom_col(data = annual_esc,
           aes(x = Species,
               y = escape))

```

## Different geoms

**Boxplot**

```{r boxplot}

annual_esc %>% 
  filter (Year == 1974,
          Species %in% c("Chum", "Pink") %>% 
  ggplot(aes(x = Species,
             y = escape))+
  geom_boxplot()

```

**Line and point**

```{r line and point}

annual_esc %>% 
  filter(Species == "Sockeye",
         SASAP.Region == "Bristol Bay") %>% 
  ggplot(aes(x = Year,
             y = escape))+
  geom_line()+
  geom_point()

```

## Customize our plot

Fill is blue inside aes

```{r}

ggplot(annual_esc,
       aes(x = Species,
           y = escape,
           fill = "blue"))+
  geom_col()

ggplot(annual_esc,
       aes(x = Species,
           y = escape,
           fill = SASAP.Region))+
  geom_col()

```

Fill is blue outside the aes

```{r}

ggplot(annual_esc,
       aes(x = Species,
           y = escape))+
  geom_col(fill = "blue")


```

